# Generated by Django 3.2 on 2021-05-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
